### ISSUE TITLE
Добавить .gitignore

### ISSUE THREAD

**Issue by coursar** [dashafromrussia/homework3.1#2]

**Comment by dashafromrussia** [comment]
1b309e480c9091845add51112bd679a7564344e6

**Comment by dashafromrussia** [comment]
@ coursar, 1b309e480c9091845add51112bd679a7564344e6

**Comment by coursar** [comment]
Issue надо закрывать коммитами, а не комментами. Т.е. в коммите пишете "Fixes #2" и когда делаете Push он сам закрывается.
